# Generated by Django 3.0.6 on 2021-01-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('size', models.CharField(max_length=50, verbose_name='Размеры')),
                ('desc_one', models.TextField(verbose_name='Описание часть 1')),
                ('desc_two', models.TextField(verbose_name='Описание часть 2')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
