# Generated by Django 3.0.6 on 2021-01-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardproduct',
            name='url',
            field=models.URLField(default=1, verbose_name='Ссылка на оригинал'),
            preserve_default=False,
        ),
    ]
