# Generated by Django 3.0.6 on 2021-01-21 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parser_site', '0002_cardproduct_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardFoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Изображение')),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='cardproduct',
            name='images',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parser_site.CardFoto', verbose_name='Изображения'),
            preserve_default=False,
        ),
    ]
