# Generated by Django 3.0.6 on 2021-01-21 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parser_site', '0006_cardfoto_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardproduct',
            name='images',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parser_site.CardFoto', verbose_name='Изображения'),
        ),
    ]
