# Generated by Django 3.0.6 on 2021-01-21 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parser_site', '0007_auto_20210121_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardfoto',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser_site.CardProduct'),
        ),
        migrations.AlterField(
            model_name='cardproduct',
            name='images',
            field=models.ImageField(null=True, upload_to='', verbose_name='CardFoto'),
        ),
    ]
