# Generated by Django 3.0.6 on 2021-01-21 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parser_site', '0008_auto_20210121_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardfoto',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parser_site.CardProduct'),
        ),
    ]
