# Generated by Django 3.0.6 on 2021-01-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_site', '0010_auto_20210121_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardproduct',
            name='images',
            field=models.ImageField(null=True, upload_to='', verbose_name='CardFoto'),
        ),
    ]
