# Generated by Django 3.0.6 on 2021-01-21 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parser_site', '0012_auto_20210121_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardproduct',
            name='images',
        ),
        migrations.AlterField(
            model_name='cardfoto',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser_site.CardProduct', verbose_name='Товар'),
        ),
    ]
