# Generated by Django 3.0.6 on 2021-01-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_site', '0014_cardproduct_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardproduct',
            name='url',
            field=models.URLField(unique=True, verbose_name='Ссылка на оригинал'),
        ),
    ]
