# Generated by Django 3.0.6 on 2021-01-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_site', '0015_auto_20210121_1530'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardfoto',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображение'},
        ),
        migrations.AddField(
            model_name='cardfoto',
            name='title',
            field=models.CharField(default=1, max_length=100, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
