# Generated by Django 3.0.6 on 2021-01-21 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_site', '0016_auto_20210121_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardfoto',
            name='title',
        ),
    ]
