# Generated by Django 3.0.6 on 2021-01-22 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parser_site', '0017_remove_cardfoto_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardproduct',
            name='section',
            field=models.CharField(default=1, max_length=100, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser_site.CardProduct')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser_site.Sections')),
            ],
        ),
    ]
