# Generated by Django 3.0.6 on 2021-01-22 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parser_site', '0018_auto_20210122_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('name_slug', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RemoveField(
            model_name='cardproduct',
            name='section',
        ),
        migrations.RemoveField(
            model_name='category',
            name='section',
        ),
        migrations.AddField(
            model_name='category',
            name='name_slug',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Sections',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parser_site.Category'),
        ),
        migrations.AddField(
            model_name='cardproduct',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parser_site.Subcategory'),
        ),
    ]
