# Generated by Django 3.0.6 on 2021-01-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_site', '0019_auto_20210122_1339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Подраздел', 'verbose_name_plural': 'Подразделы'},
        ),
        migrations.AlterField(
            model_name='cardproduct',
            name='desc_two',
            field=models.TextField(null=True, verbose_name='Описание часть 2'),
        ),
    ]
