# Generated by Django 3.0.6 on 2021-01-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_site', '0020_auto_20210124_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardproduct',
            name='size',
            field=models.CharField(max_length=50, null=True, verbose_name='Размеры'),
        ),
    ]
