# Generated by Django 3.0.6 on 2021-02-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_site', '0023_auto_20210124_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardproduct',
            name='slug',
            field=models.CharField(blank=True, max_length=100, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='cardproduct',
            name='url',
            field=models.URLField(default=1, unique=True, verbose_name='Ссылка на оригинал'),
            preserve_default=False,
        ),
    ]
