# Generated by Django 3.0.6 on 2021-02-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_site', '0024_auto_20210201_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardproduct',
            name='desc_one',
            field=models.TextField(blank=True, null=True, verbose_name='Описание часть 1'),
        ),
        migrations.AlterField(
            model_name='cardproduct',
            name='desc_two',
            field=models.TextField(blank=True, null=True, verbose_name='Описание часть 2'),
        ),
        migrations.AlterField(
            model_name='cardproduct',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='CardFoto'),
        ),
        migrations.AlterField(
            model_name='cardproduct',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Размеры'),
        ),
    ]
