# Generated by Django 3.0.6 on 2021-02-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_site', '0025_auto_20210201_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardproduct',
            name='url_slug',
            field=models.SlugField(blank=True, max_length=130, verbose_name='URL_slug'),
        ),
    ]
