# Generated by Django 3.0.6 on 2021-02-01 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_site', '0026_cardproduct_url_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardproduct',
            name='url_slug',
        ),
    ]
