# Generated by Django 3.0.6 on 2021-02-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_site', '0029_auto_20210202_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='sorted',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сортировка'),
        ),
    ]
