# Generated by Django 3.0.6 on 2021-02-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_site', '0030_subcategory_sorted'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardfoto',
            name='sorted',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
