# Generated by Django 3.0.6 on 2021-02-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_site', '0031_cardfoto_sorted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardfoto',
            options={'ordering': ['sorted'], 'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображение'},
        ),
        migrations.AddField(
            model_name='subcategory',
            name='view_menu',
            field=models.BooleanField(default=True, verbose_name='Показывать в меню'),
        ),
    ]
