# Generated by Django 3.1.5 on 2021-02-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_site', '0034_remove_cardproduct_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardproduct',
            name='subcategory',
            field=models.ManyToManyField(null=True, to='parser_site.Subcategory', verbose_name='Разделы'),
        ),
    ]
