# Generated by Django 3.0.6 on 2021-02-12 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parser_site', '0035_auto_20210206_0911'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagehit',
            name='product',
            field=models.ForeignKey(default=92, on_delete=django.db.models.deletion.DO_NOTHING, to='parser_site.CardProduct', verbose_name='Товар'),
            preserve_default=False,
        ),
    ]
