# Generated by Django 3.0.6 on 2021-02-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_remove_pagehit_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagehit',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
