# Generated by Django 3.1.5 on 2021-02-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_auto_20210205_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Количество'),
        ),
    ]
